name: Manual Approval
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      pull_number:
        description: "Pull Request to approve"
        required: true
jobs:
  mark-pending:
    name: Mark PR as pending
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const sha = context.payload.pull_request.head.sha;
            const data = await github.repos.createStatus({
              ...context.repo,
              sha,
              state: "pending",
              context: "manual-approval",
              description: "This PR needs manual approval"
            });

  approve:
    name: Approve PR
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          actor: ${{ github.actor }}
          script: |
            const pull_number = context.payload.inputs.pull_number;

            const {data: pr} = github.pulls.get({
              ...context.repo,
              pull_number
            });
            const sha = pr.head.sha;

            const data = await github.repos.createStatus({
              ...context.repo,
              sha,
              state: "success",
              context: "manual-approval",
              description: `Manual approval provided by ${core.getInput('actor')}`
            });
