name: "Push + Release"
on: push
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run NPM test
        run: echo npm test
      - name: Release
        run: echo npm publish
        if: github.ref == 'refs/heads/develop'

