name: Artifact
on: [push, pull_request]
jobs:
  artifact:
    runs-on: ubuntu-20.04
    steps:
      #- run: |
      #    export NVM_DIR=$HOME/.nvm
      #    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      #    nvm install 14 && nvm use 14
      - uses: mheap/node14-action@master
